//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FourDeep.PDizzle
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "pdizzle";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PDizzle";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"4Deep Technologies";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PDizzleDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PDizzleCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PDizzleExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PDizzleCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPDizzleExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PDizzleCommandSetId), 0x0001);
	
		// Package identifier
		public const string PDizzlePackageId = "bc1d75bb-efe3-43d0-a087-c9c3d3829594";
		
		// Editor factory identifier
		public const string PDizzleEditorFactoryId = "8ba44c80-41ae-4880-97d2-ebe8b913162f";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PDizzleModelExplorerToolWindowId = "44c6af61-3646-40ee-96cd-6ca59840146b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace FourDeep.PDizzle
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PDizzleCommandSetId = "4e0d3153-7f5d-4ac8-b8af-d97e65103bf6";
	}
}